name: CI

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      # Frontend
      - name: Build frontend image
        run: docker build -t asplund1/frontend:latest ./frontend

      - name: Run frontend tests
        run: |
          npm install
          npm test
        working-directory: ./frontend

      # API
      - name: Build API image
        run: docker build -t asplund1/api:latest ./api

      - name: Run API tests
        run: |
          npm install
          npm test
        working-directory: ./api